# AUTOGENERATED! DO NOT EDIT! File to edit: ../../03.01_backpropagation_rebuild.ipynb.

# %% auto 0
__all__ = ['path_data', 'path_gz', 'x_train', 'y_train', 'x_valid', 'y_valid', 'n', 'm', 'c', 'nh', 'w1', 'b1', 'w2', 'b2']

# %% ../../03.01_backpropagation_rebuild.ipynb 1
import pickle,gzip,math,os,time,shutil,torch,matplotlib as mpl, numpy as np
from pathlib import Path
from torch import tensor
from fastcore.test import test_close
torch.manual_seed(42)
import tsensor
# Get rid of findfont: Font family 'Arial' not found.
# when running a remote notebook on Jupyter Server on Ubuntu Linux server
import logging
logging.getLogger("matplotlib.font_manager").setLevel(logging.ERROR)

from lolviz import *


mpl.rcParams['image.cmap'] = 'gray'
torch.set_printoptions(precision=2, linewidth=125, sci_mode=False)
np.set_printoptions(precision=2, linewidth=125)

path_data = Path('data')
path_gz = path_data/'mnist.pkl.gz'
with gzip.open(path_gz, 'rb') as f: ((x_train, y_train), (x_valid, y_valid), _) = pickle.load(f, encoding='latin-1')
x_train, y_train, x_valid, y_valid = map(tensor, [x_train, y_train, x_valid, y_valid])

# %% ../../03.01_backpropagation_rebuild.ipynb 8
n,m = x_train.shape
c = y_train.max()+1

# %% ../../03.01_backpropagation_rebuild.ipynb 10
nh = 50

# %% ../../03.01_backpropagation_rebuild.ipynb 13
w1 = torch.randn(m,c)
b1 = torch.zeros(nh)
w2 = torch.randn(nh,1)
b2 = torch.zeros(1)
